services:
  app:
    build: .
    container_name: wrkspace-expressjs
    command: npm run dev
    environment:
      NODE_ENV: development
      PORT: 3000
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    restart: unless-stopped
